name: Update README with latest release

on:
  release:
    types: [published]
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set the latest release version
      id: set_version
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          echo "tag=$(echo $GITHUB_REF | sed 's/refs\/tags\///')" >> $GITHUB_ENV
        else
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "tag=${latest_tag}" >> $GITHUB_ENV
        fi

    - name: Update README
      run: |
        latest_version=${{ env.tag }}
        sed -i "s#releases/download/app-v[0-9.]*/Ableton.Live.Manager_[0-9.]*_universal.dmg#releases/download/app-v${latest_version}/Ableton.Live.Manager_${latest_version}_universal.dmg#g" README.md
        sed -i "s#releases/download/app-v[0-9.]*/Ableton.Live.Manager_[0-9.]*_x64_en-US.msi#releases/download/app-v${latest_version}/Ableton.Live.Manager_${latest_version}_x64_en-US.msi#g" README.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout main
        git pull origin main
        git add README.md
        git commit -m "Update README with latest release version ${latest_version}"
        git push origin main
